# fly.toml app configuration file generated for pizza-order-web-broken-sun-4994 on 2025-02-16T17:52:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pizza-order-web-broken-sun-4994'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
