# fly.toml app configuration file generated for pizza-order-web on 2025-02-16T17:20:12-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pizza-order-web'
primary_region = 'dfw'
dockerfile = "Dockerfile"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
